repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.9
    hooks:
      - id: pylint
        args: [
            "--rcfile=.pylintrc", # Link to your config file
            "--disable=E0401", # import errors are can be misidentified due to PATH issues
          ]